export let phrases = [
	["by the way", "кстати"],
	["before i forget", "пока я не забыл"],
	["that being said", "тем не менее"],
	["that reminds me", "напоминает мне"],
	["its been so long", "давно не виделись"],
	["take it easy", "не напрягайся"],
	["calm down", "успокойся"],
	["no worries", "ничего страшного"],
	["catch you later", "скоро увидимся"],
	["im on my way", "я уже в пути"],
	["hang on a sec", "подожди секундочку"],
	["i will be right back", "скоро вернусь"],
	["im running late", "я опаздываю"],
	["im starving", "я умираю с голода"],
	["im beat", "я устал"],
	["all set", "готов"],
	["no big deal", "ничего особенного"],
	["that make sense", "это имеет смысл"],
	["i will keep your posted", "я буду держать тебя в курсе"],
	["im in", "я в деле, я за"],
	["thats awesome", "это превосходно"],
	["are you kidding me?", "ты издеваешься?"],
	["can you give me a hand?", "можешь мне помочь?"],
	["its up to you", "выбор за тобой, решать тебе"],
	["lets play it by ear", "разберемся"],
	["i couldnt agree more", "я полностью согласен"],
	["whats going on?", "что происходит?"],
	["it slipped my mind", "вылетело из головы"],
	["fingers crossed", "скрестить пальцы (молимся, что все получится)"],
	["better late then never", "лучше поздно чем никогда"],
	["time flies", "время летит быстро"],
	["its not my cup of tea", "мне это не очень нравится ( не в моем вкусе)"],
	["lets call it a day", "на сегодня закругляемся"],
	["break a leg!", "удачи!"],
	["im all ears", "я весь во внимании"],
	["what's the catch?", "в чем подвох?"],
]