export let irregularVerbs = [
	['be was were been', 'быть, являться'],
	['beat beat beat', 'бить'],
	['become became become', 'становиться'],
	['begin began begun', 'начинать'],
	['bite bit bitten', 'кусать'],
	['blow blew blown', 'дуть, выдыхать'],
	['break broke broken', 'ломать, разбивать, разрушать'],
	['bring	brought	brought', 'приносить, привозить, доставлять'],
	['build built built', 'строить'],
	['buy bought bought', 'покупать'],
	['catch caught caught', 'ловить, поймать'],
	['choose chose chosen', 'выбирать'],
	['come came come', 'приходить'],
	['cost cost cost', 'стоить'],
	['cut cut cut', 'резать'],
	['deal dealt dealt', 'иметь дело, распределять'],
	['dig dug dug', 'копать, рыть'],
	['do did done', 'делать'],
	['draw drew drawn', 'рисовать'],
	['drink drank drunk', 'пить'],
	['drive drove driven', 'ездить, водить'],
	['eat ate eaten', 'есть'],
	['fall fell fallen', 'падать'],
	['feed fed fed', 'кормить'],
	['feel felt felt', 'чувствовать, ощущать'],
	['fight fought fought', 'драться, сражаться'],
	['find found found', 'находить'],
	['fly flew flown', 'летать'],
	['forget forgot forgotten', 'забывать'],
	['forgive forgave forgiven', 'прощать'],
	['freeze froze frozen', 'замерзать'],
	['get got got', 'получать'],
	['give gave given', 'дать'],
	['go went gone', 'идти'],
	['grow grew grown', 'расти'],
	['hang hung hung', 'вешать, висеть'],
	['have had had', 'иметь'],
	['hear heard heard', 'слышать'],
	['hide hid hidden', 'прятать'],
	['hit hit hit', 'ударять'],
	['hold held held', 'держать, задерживать'],
	['hurt hurt hurt', 'ранить'],
	['keep kept kept', 'хранить, сохранять'],
	['know knew known', 'знать'],
	['lay laid laid', 'класть, положить'],
	['lead led led', 'вести, сопровождать'],
	['leave left left', 'покидать, оставлять'],
	['lend lent lent', 'одалживать'],
	['let let let', 'позволять, разрешать'],
	['lie lay lain', 'лежать'],
	['light lit lit', 'светиться, зажигать'],
	['lose lost lost', 'терять, проигрывать'],
	['make made made', 'делать, создавать'],
	['mean meant meant', 'значить, иметь в виду'],
	['meet met met', 'встречать, знакомиться'],
	['pay paid paid', 'платить'],
	['put put put', 'класть, ставить'],
	['read read read', 'читать'],
	['ride rode ridden', 'кататься, ехать верхом'],
	['ring rang rung', 'звенеть, звонить'],
	['rise rose risen', 'восходить, вставать'],
	['run ran run', 'бегать'],
	['say said said', 'говорить, сказать'],
	['see saw seen', 'видеть'],
	['seek sought sought', 'искать'],
	['sell sold sold', 'продавать'],
	['send sent sent', 'отправлять'],
	['set set set', 'устанавливать, задавать'],
	['shake shook shaken', 'трясти'],
	['shine shone shone', 'светить, сиять'],
	['shoot shot shot', 'стрелять'],
	['show showed shown', 'показывать'],
	['shut shut shut', 'запирать, закрывать'],
	['sing sang sung', 'петь'],
	['sink sank sunk', 'тонуть'],
	['sit sat sat', 'сидеть, садиться'],
	['sleep slept slept', 'спать'],
	['speak spoke spoken', 'говорить, разговаривать'],
	['spend spent spent', 'тратить'],
	['stand stood stood', 'стоять'],
	['steal stole stolen', 'воровать, красть'],
	['stick stuck stuck', 'втыкать, приклеивать'],
	['sweep swept swept', 'мести, подметать'],
	['swim swam swum', 'плавать'],
	['swing swung swung', 'качаться, вертеться'],
	['take took taken', 'брать, взять'],
	['teach taught taught', 'учить'],
	['tear tore torn', 'рвать, отрывать'],
	['tell told told', 'рассказывать'],
	['think thought thought', 'думать'],
	['throw threw thrown', 'бросать, кидать, метать'],
	['understand understood understood', 'понимать'],
	['wake woke woken', 'просыпаться, будить'],
	['wear wore worn', 'носить (одежду)'],
	['win won won', 'побеждать'],
	['write wrote written', 'писать'],
]